#### Indexing with Two-Dimensional arrays

In [3]:
import numpy as np

In [4]:
grades = np.array([[87, 96, 70], [100, 87, 90],
    [94, 77, 90], [100, 81, 82]])

In [5]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [6]:
grades[0, 1]    # row 0, column 1

96

#### Selecting a Subset of a Two-Dimensional array's Rows

In [7]:
grades[1]

array([100,  87,  90])

In [8]:
# To select multiple sequential rows, use slice notation:
grades[0:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

In [9]:
# To select multiple non-sequential rows, use a list of row indices
grades[[1, 3]]

array([[100,  87,  90],
       [100,  81,  82]])

#### Selecting a Subset of a Two-Dimensional array's Columns

In [10]:
grades[:, 0]

array([ 87, 100,  94, 100])

In [11]:
# We can select consecutive columns using a slice
grades[:, 1:3]

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [12]:
# or specific columns using a list of column indices
grades[:, [0, 2]]

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])