In [1]:
import numpy as np

In [2]:
numbers = np.arange(1, 6)

In [3]:
numbers

array([1, 2, 3, 4, 5])

In [4]:
numbers2 = numbers.view()

In [5]:
numbers2

array([1, 2, 3, 4, 5])

#### We can use the built-in id function to see that numbers and numbers2 are different objects:

In [6]:
id(numbers)

1465064373664

In [7]:
id(numbers2)

1465056313056

In [8]:
numbers[1] *= 10

In [9]:
numbers2

array([ 1, 20,  3,  4,  5])

In [10]:
numbers

array([ 1, 20,  3,  4,  5])

In [11]:
numbers2[1] /= 10

In [12]:
numbers

array([1, 2, 3, 4, 5])

In [13]:
numbers2

array([1, 2, 3, 4, 5])

#### Slice Views

In [14]:
numbers2 = numbers[0:3]

In [15]:
numbers2

array([1, 2, 3])

In [16]:
id(numbers)

1465064373664

In [17]:
id(numbers2)

1465006041088

In [18]:
numbers[1] *= 20

In [19]:
numbers

array([ 1, 40,  3,  4,  5])

In [20]:
numbers2

array([ 1, 40,  3])