In [1]:
import numpy as np

In [2]:
numbers = np.arange(1, 6)

In [3]:
numbers

array([1, 2, 3, 4, 5])

In [4]:
numbers2 = numbers.copy()

In [5]:
numbers2

array([1, 2, 3, 4, 5])

In [6]:
numbers[1] *= 10

In [7]:
numbers

array([ 1, 20,  3,  4,  5])

In [8]:
numbers2

array([1, 2, 3, 4, 5])