In [1]:
import numpy as np

In [2]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [3]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [4]:
grades.reshape(1, 6)

array([[ 87,  96,  70, 100,  87,  90]])

In [5]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [6]:
grades.resize(1, 6)

In [7]:
grades

array([[ 87,  96,  70, 100,  87,  90]])

#### flatten vs. ravel

In [8]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [9]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [10]:
flattened = grades.flatten()

In [11]:
flattened

array([ 87,  96,  70, 100,  87,  90])

In [12]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [13]:
flattened[0] = 100

In [14]:
flattened

array([100,  96,  70, 100,  87,  90])

In [15]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

#### Method ravel produces a view of the original array, which shares the grades array's data:

In [16]:
raveled = grades.ravel()

In [17]:
raveled

array([ 87,  96,  70, 100,  87,  90])

In [18]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [19]:
raveled[0] = 100

In [20]:
raveled

array([100,  96,  70, 100,  87,  90])

In [21]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

#### Transposing Rows and Columns

In [22]:
grades.T

array([[100, 100],
       [ 96,  87],
       [ 70,  90]])

In [23]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

In [24]:
grades2 = np.array([[94, 77, 90], [100, 81, 82]])

In [25]:
np.hstack((grades, grades2))

array([[100,  96,  70,  94,  77,  90],
       [100,  87,  90, 100,  81,  82]])

In [26]:
np.vstack((grades, grades2))

array([[100,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])