In [1]:
import numpy as np

#### Arithmetic Operations with arrays and Individual Numeric Values

In [2]:
numbers = np.arange(1, 6)

In [3]:
numbers

array([1, 2, 3, 4, 5])

In [4]:
numbers * 2

array([ 2,  4,  6,  8, 10])

In [5]:
numbers ** 3

array([  1,   8,  27,  64, 125], dtype=int32)

In [6]:
numbers

array([1, 2, 3, 4, 5])

In [7]:
numbers += 10

In [8]:
numbers

array([11, 12, 13, 14, 15])

In [9]:
numbers * [2, 2, 2, 2, 2]

array([22, 24, 26, 28, 30])

#### Arithmetic Operations Between arrays

In [10]:
numbers2 = np.linspace(1.1, 5.5, 5)

In [11]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [12]:
numbers * numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

#### Comparing arrays

In [13]:
numbers

array([11, 12, 13, 14, 15])

In [14]:
numbers >= 13

array([False, False,  True,  True,  True])

In [15]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [16]:
numbers2 < numbers

array([ True,  True,  True,  True,  True])

In [17]:
numbers == numbers2

array([False, False, False, False, False])

In [18]:
numbers == numbers

array([ True,  True,  True,  True,  True])