In [1]:
import numpy as np

In [3]:
grades = np.array([[87, 96, 70], [100, 87, 90],
    [94, 77, 90], [100, 81, 82]])

In [4]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [5]:
grades.sum()

1054

In [6]:
grades.min()

70

In [7]:
grades.max()

100

In [8]:
grades.mean()

87.83333333333333

In [9]:
grades.std()

8.792357792739987

In [10]:
grades.var()

77.30555555555556

#### Calculations by Row or Column

In [11]:
grades.mean(axis=0)

array([95.25, 85.25, 83.  ])

In [12]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])