In [1]:
import numpy as np

In [2]:
numbers = np.array([1, 4, 9, 16, 25, 36])

In [3]:
np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [4]:
numbers2 = np.arange(1, 7) * 10

In [5]:
numbers2

array([10, 20, 30, 40, 50, 60])

In [7]:
np.add(numbers, numbers2)

array([11, 24, 39, 56, 75, 96])

#### Broadcasting with Universal Functions

In [8]:
np.multiply(numbers2, 5)

array([ 50, 100, 150, 200, 250, 300])

#### Reshaping numbers2

In [9]:
numbers3 = numbers2.reshape(2, 3)

In [10]:
numbers3

array([[10, 20, 30],
       [40, 50, 60]])

In [11]:
numbers4 = np.array([2, 4, 6])

In [12]:
np.multiply(numbers3, numbers4)

array([[ 20,  80, 180],
       [ 80, 200, 360]])